FROM node:20-alpine

# Set the working directory
WORKDIR /app/backend

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and config
COPY . .

# Build the application
RUN npm run build

CMD ["npm", "run", "start"]